#https://home-assistant.io/components/binary_sensor/

#motion
- platform: mqtt
  name: "Motion Detected"
  state_topic: "pi/motion_detected"

# doors
- platform: mqtt
  state_topic: "pi/front_door"
  name: "Front Door"
  payload_on: "Open"
  payload_off: "Closed"
  device_class: opening
#
# - platform: template
#   sensors:
#     front_door:
#       value_template:  '{%- if is_state("binary_sensor.front_door", "on") -%} Open {%- else -%} Closed {%- endif -%}'
#       icon_template:  '{%- if is_state("binary_sensor.front_door", "on") -%} mdi:door-open {%- else -%} mdi:door-closed {%- endif -%}'

- platform: mqtt
  state_topic: "pi/bilco_door"
  name: "Bilco Door"
  payload_on: "Open"
  payload_off: "Closed"
  device_class: opening

- platform: mqtt
  state_topic: "pi/basement_door"
  name: "Basement Door"
  payload_on: "Open"
  payload_off: "Closed"
  device_class: opening

- platform: mqtt
  state_topic: "pi/porch_door"
  name: "Porch Door"
  payload_on: "Open"
  payload_off: "Closed"
  device_class: opening

#windows
- platform: mqtt
  state_topic: "pi/basement_window_nw"
  name: "Basement Window NW"
  payload_on: "Open"
  payload_off: "Closed"
  device_class: opening
