homeassistant:
  name: Barn
  customize: !include customize.yaml
  packages: !include_dir_named packages
  latitude: !secret latitude_barn
  longitude: !secret longitude_barn
  elevation: 101
  unit_system: imperial
  time_zone: America/New_York
  temperature_unit: F


#After Lovelace
weather:
 - platform: darksky
   api_key: !secret dark_sky_key

#legacy
frontend:
logbook:
updater:
config:
sun:
discovery:
#history:
logger:

http:
  api_password: !secret http_password
  trusted_networks:
    - 192.168.1.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3

notify:
  - name: gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret ha_gmail_username_eric
    encryption: starttls
    username: !secret gmail_username
    password: !secret gmail_password
    recipient:
      - !secret ha_gmail_username_eric
      #- !secret ha_gmail_username_ash
    sender_name: The Barn

zone:
  - name: Home
    latitude: !secret latitude_barn
    longitude: !secret longitude_barn
    radius: 150
    icon: mdi:domain

  - name: Barn
    latitude: !secret latitude_barn
    longitude: !secret longitude_barn
    radius: 150
    icon: mdi:domain

  - name: City
    latitude: !secret latitude_city
    longitude: !secret longitude_city
    radius: 150
    icon: mdi:domain

  - name: Poughkeepsie Train
    latitude: 41.7071475
    longitude: -73.9398788

  - name: Grand Central
    latitude: 40.752457
    longitude: -73.9805987

climate:
   platform: honeywell
   username: !secret thermostat_name
   password: !secret thermostat_password
   region: us
   scan_interval: 600

camera:
 - platform: mjpeg
   name: Barn Inside
   username: !secret camera_name
   password: !secret camera_password
   authentication: basic
   mjpeg_url: https://camera.01tools.com/picture/1/frame/

camera 1:
 - platform: mjpeg
   name: Barn Outside
   username: !secret camera_name
   password: !secret camera_password
   authentication: basic
   mjpeg_url: https://outsidecamera.01tools.com/picture/1/frame/

camera 2:
 - platform: generic
   still_image_url: https://511ny.org/map/Cctv/4616569--17
   name: West Side Highway at 158th

camera 3:
 - platform: generic
   still_image_url: https://511ny.org/map/Cctv/muuvdoatpie--13
   name: Saw Mill River

eufy:
  username: !secret eufy_username
  password: !secret eufy_password

# device_tracker:
#   - platform: asuswrt
#     host: !secret router_ip
#     username: !secret router_username
#     password: !secret router_password
#     track_new_devices: no
#     protocol: telnet
#   - platform: owntracks_http

# asuswrt:
#   host: !secret router_ip
#   username: !secret router_username
#   password: !secret router_password

apcupsd:
  host: !secret apc_host
  port: !secret apc_port

mqtt:
  broker: 192.168.1.211
  protocol: 3.1

switch:
  - platform: tplink
    host: 192.168.1.203
    name: Beer Fan
  - platform: tplink
    #host: !secret tplink_host
    host: 192.168.1.204
    name: Drip Irrigation
  - platform: tplink #washer
    host: 192.168.1.205
    name: Power Monitor

media_player:
  - platform: plex

# sonos:
#   media_player:
#     hosts:
#       - 192.168.1.209
#       - 192.168.1.99
tts:
  - platform: google

notify:
  - name: notify
    platform: html5
    gcm_api_key: !secret chrome_push_server_key
    gcm_sender_id: !secret chrome_push_sender_id

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

panel_iframe:
  otherapp:
    title: 'Motioneye'
    url: 'https://admin-camera1.01tools.com'
    icon: mdi:eye

person:

influxdb:
  host: 192.168.1.208
  include:
    entities:
       - sensor.to_barn
       - sensor.to_city
       - sensor.dark_sky_apparent_temperature
       #- sensor.dark_sky_precip_intensity
       - climate.barn
       - sun.sun
       - binary_sensor.front_door
       - binary_sensor.basement_door
       - binary_sensor.porch_door
       - binary_sensor.bilco_door
       - switch.powermonitor
       - switch.drip_irrigation
       - sensor.dark_sky_precip_probability
       - sensor.dark_sky_daily_max_precip_intensity

automation: !include_dir_merge_list automation
group: !include groups.yaml
sensor: !include_dir_merge_list sensor
binary_sensor: !include binary_sensor.yaml
script: !include_dir_merge_named script
python_script:
