homeassistant:
  #name: Barn
  customize: !include customize.yaml
  packages: !include_dir_named packages
  latitude: !secret latitude_barn
  longitude: !secret longitude_barn
  elevation: 101
  unit_system: imperial
  time_zone: America/New_York
  temperature_unit: F

# Show links to resources in log and frontend
frontend:
logbook:
updater:
config:
sun:
#discovery:
history:

http:
  api_password: !secret http_password
  #base_url: iot.angrylab.com
  trusted_networks:
    - 192.168.1.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3
  #server_port:

notify:
  - name: gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret ha_gmail_username_eric
    encryption: starttls
    username: !secret gmail_username
    password: !secret gmail_password
    recipient:
      - !secret ha_gmail_username_eric
      - !secret ha_gmail_username_ash
    sender_name: The Barn

zone:
  name: Barn
  latitude: !secret latitude_barn
  longitude: !secret longitude_barn
  radius: 150
  icon: mdi:domain

zone 2:
  name: City
  latitude: !secret latitude_city
  longitude: !secret longitude_city
  radius: 150
  icon: mdi:domain

climate:
   platform: honeywell
   username: !secret thermostat_name
   password: !secret thermostat_password
   region: us
   scan_interval: 600
   heat_away_temperature: 51

camera:
 - platform: generic
   name: Barn Inside
   username: !secret camera_name
   password: !secret camera_password
   still_image_url: http://camera.angrylab.com:8082/picture/1/frame/

camera 2:
 - platform: generic
   still_image_url: https://511ny.org/map/Cctv/4616569--17
   name: West Side Highway at 158th

camera 3:
 - platform: generic
   still_image_url: https://511ny.org/map/Cctv/muuvdoatpie--13
   name: Saw Mill River

device_tracker:
  - platform: asuswrt
    host: !secret router_ip
    username: !secret router_username
    password: !secret router_password
    track_new_devices: yes
    protocol: telnet

apcupsd:
  host: !secret apc_host
  port: !secret apc_port

mqtt:
  broker: 192.168.1.211
  protocol: 3.1

switch:
  - platform: tplink
    host: !secret tplink_host

media_player:
  - platform: sonos
    hosts:
      - 192.168.1.209
      - 192.168.1.99

tts:
  - platform: google

shell_command:
  snapshot: python /config/alarmsnapshot.py
  cookie: curl -d "username="!secret zoneminder_username"&password="!secret zoneminder_password"&action=login&view=console" -c /config/cookies.txt  https://"!secret zoneminder_url"/zm/index.php
  modect: curl -XPOST "https://"!secret zoneminder_url"/zm/api/monitors/3.json" -d "Monitor[Function]=Modect&Monitor[Enabled]=1"

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

automation: !include_dir_merge_list automation
group: !include groups.yaml
sensor: !include_dir_merge_list sensor
binary_sensor: !include binary_sensor.yaml
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean
