title: Welcome to the Barn
# Exclude entities from "Unused entities" view
views:
    # View tab title.
  - title: Home
    # Optional unique id for direct access /lovelace/${id}
    id: example
    # Each view can have a different theme applied.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - device_tracker.paulus
          - device_tracker.anne_there
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home

      - type: weather-forecast
        entity: group.weather_card_today
      - type: entities
        entities:
          - group.weather_card_forecast
          - group.thermostat
          - media_player.patio
          - media_player.living_room
    # Title of the view. Will be used as the tooltip for tab icon
    title: Security
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - light.kitchen
          - switch.ac
          - entity: light.living_room
            # Override the name to use
            name: LR Lights

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
    title: Travel
    title: System
