- platform: gtfs
  origin: 51
  destination: 1
  data: metro_north.zip
  name: poughkeepsie_leaving1
  offset:
    minutes: 45

- platform: gtfs
  origin: 51
  destination: 1
  data: metro_north.zip
  name: barn_to_city2
  offset:
    minutes: 60
