##Source - https://www.home-assistant.io/components/sensor.gtfs/
## metro_north.zip must exist in home-assistant/config/gtfs folder
## To update the data, delete the SQLite3 file and restart Home Assistant.

- platform: gtfs
  origin: 51
  destination: 1
  data: metro_north.zip
  name: barn_to_city1
  offset:
    minutes: 45

- platform: gtfs
  origin: 51
  destination: 1
  data: metro_north.zip
  name: barn_to_city2
  offset:
    minutes: 90
