- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /media
    - type: last_boot
    - type: memory_free
- platform: apcupsd
  resources:
    - loadpct
    - bcharge
    - timeleft
