- platform: template
  sensors:
    beaker:
      value_template:  '{% if is_state("device_tracker.beaker", "home") %} Online {% else %} Offline {%- endif %}'
    ashleighsipad:
      value_template:  '{% if is_state("device_tracker.ashleighsipad", "home") %} Online {% else %} Offline {%- endif %}'
    outside_temp:
      value_template: '{{ states.sensor.dark_sky_temperature.state | round(0) }}'
      unit_of_measurement: '°F'
      friendly_name: 'Temp'
    temp_high:
      value_template: '{{ states.sensor.dark_sky_daily_high_temperature.state | round(0) }}'
      unit_of_measurement: '°F'
      friendly_name: "Today's High"
    temp_low:
      value_template: '{{ states.sensor.dark_sky_daily_low_temperature.state | round(0) }}'
      unit_of_measurement: '°F'
      friendly_name: "Today's Low"
    poughkeepsie_leaving1:
      value_template: '{{states.sensor.barn_to_city1.attributes["Origin Stop Arrival Time"]}}'
      friendly_name: "Next train leaves Poughkeepsie at: "
    poughkeepsie_arrives1:
      value_template: '{{states.sensor.barn_to_city1.attributes["Destination Stop Arrival Time"]}}'
      friendly_name: "Next train arrives at Grand Central at: "
    front_door:
      value_template:  '{% if is_state("binary_sensor.front_door", "on") %} Open {% else %} Closed {%- endif %}'
      icon_template:  '{% if is_state("binary_sensor.front_door", "on") %} mdi:door-open {% else %} mdi:door-closed {%- endif %}'
