- platform: template
  sensors:
    beaker:
      value_template:  '{% if is_state("device_tracker.beaker", "home") %} Online {% else %} Offline {%- endif %}'
    ashleighsipad:
      value_template:  '{% if is_state("device_tracker.ashleighsipad", "home") %} Online {% else %} Offline {%- endif %}'
    outside_temp:
      value_template: '{{ states.sensor.dark_sky_temperature.state | round(0)}}'
      unit_of_measurement: '°F'
      friendly_name: 'Temp'
