- platform: darksky
  api_key: !secret dark_sky_key
  monitored_conditions:
    - summary
    - icon
    - temperature
    - apparent_temperature
    - precip_probability
    - precip_intensity
    - temperature_max
    - temperature_min
    - hourly_summary
