- alias: Away Mode
  initial_state: 'on'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.front_door
      - binary_sensor.basement_door
      - binary_sensor.porch_door
      - binary_sensor.bilco_door
    to: 'on'  #open
    from: 'off'

  action:
    #Enable Email
    #- service: script.alarm_notification
    - service: notify.notify
      data:
        title: 'Door Alarm'
        message: 'The {{ trigger.to_state.attributes.friendly_name }} door has been opened'
        data:
          images:
            - /config/www/barn.png
