- alias: Away Mode
  initial_state: 'on'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.front_door
      - binary_sensor.basement_door
      - binary_sensor.porch_door
      - binary_sensor.bilco_door
    from: 'off'
    to: 'on'  #open

  action:
    #Enable Email
    #- service: script.alarm_notification
    - service: notify.notify
      data_template:
        title: "Door Alarm"
        message: "The {{ trigger.from_state.attributes.friendly_name }} has been opened"
