- alias: Away Mode
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: 'on'  #open
    from: 'off'
  condition: state
    entity_id: input_boolean.away
    state: 'on'

  action:
    #- service: script.alarm_notification
    - service: shell_command.cookie
    - delay:
        seconds: 1
    - service: shell_command.modect
    - service: persistent_notification.create
      data:
        message: "alarm triggered"
        title: "Alarm"
