- alias: Away Mode
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: 'on'  #open
    from: 'off'

  action:
    #Enable Email
    #- service: script.alarm_notification
    - service: persistent_notification.create
      data:
        message: "alarm triggered"
        title: "Door Alarm"
    - service: notify.gmail
      data:
        title: 'Front Door Alarm'
        message: '<b>Front</b> Door Alarm Triggered'
        data:
          images:
            - /config/www/barn.png
