####Notify if door is open for more than 5 minutes

- alias: 'Door Open Alarm'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off' #closed
    to: 'on' #open
    for:
      minutes: 5

  action:
    #- service: script.door_notification
    service: notify.gmail
      data:
        title: 'Door Alarm'
        message: 'Door has been open for more than 5 minutes'
        data:
          images:
            - /config/www/barn.png
    - #service: tts.google_say
      #data:
      #  entity_id: media_player.patio
      #  message: The door is ajar
