####Notify if door is open for more than 5 minutes

- alias: 'Door Open Alarm'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off' #closed
    to: 'on' #open
    for:
      minutes: 5

  action:
  - service: tts.google_say
    entity_id: media_player.living_room
    data:
      message: 'The door is ajar'
  - service: notify.gmail
    data:
      title: 'Door Open Alarm'
      message: 'Door is ajar'
      data:
        images:
          - /config/www/barn.png
