####Notify if door is open for more than 5 minutes

- alias: 'Door Open'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off' #closed
    to: 'on' #open
    for:
      minutes: 5

  action:
    #- service: script.door_notification
    - service: persistent_notification.create
      data:
        message: "A door has been open for more than 5 minutes"
        title: "Door Ajar"
