####Turn on heat for Henry
##Every friday at 6:00pm

- alias: 'Friday Heat'
  trigger:
    platform: time
    at: "18:00:00"
  condition:
  - condition: time
    weekday:
       - fri
  - condition: state
    entity_id: 'input_boolean.heat'
    state: 'on'

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.barn
        temperature: 76
        operation_mode: Heat
    - service: script.heat_notification
