####Turn on heat for Henry
##Every friday at 6:00pm

- alias: 'Friday Heat'
  initial_state: 'on'
  trigger:
    platform: time
    at: "13:08:00"
  condition:
  - condition: time
    weekday:
       - mon

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.barn
        temperature: 76
        operation_mode: Heat
    #- service: script.heat_notification
