####Turn on heat for Henry


- alias: 'Heat on for Henry'
  trigger:
    platform: time
    at: "13:50:00"
  condition:
  - condition: time
    weekday:
      - tue
      - thu
  action:
    - service: climate.set_temperature
    - data:
        entity_id: climate.barn
        temperature: 76
        operation_mode: Heat
    - service: script.alarm_notification
