####Turn on heat for Henry
##Every friday at 6:00pm

- alias: 'Heat on for Henry'
  trigger:
    platform: time
    at: "12:50:00"
  condition:
  - condition: time
    weekday:
      - thu
      - fri
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.barn
        temperature: 76
        operation_mode: Heat
    - service: script.heat_notification
