- alias: Motion Detection
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_detected
    to: 'on'
    from: 'off'

  action:
    #Enable Email
    #- service: script.alarm_notification
    - service: notify.notify
      data:
        title: 'Motion Detected'
        message: 'Motion Alarm Triggered'
    # - service: notify.gmail
    #   data:
    #     title: 'Motion Detected'
    #     message: 'Motion Alarm Triggered'
    #     data:
    #       images:
    #         - /config/www/barn.png
