- alias: Motion
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_detected
    to: 'on'
    from: 'off'

  action:
    #Enable Email
    #- service: script.alarm_notification
    - service: notify.gmail
      data:
        title: 'Motion Detected'
        message: 'Motion Alarm Triggered'
        data:
          images:
            - /config/www/barn.png
