# Washer Notification Sequence Done
- alias: 'Washer Done'
  trigger:
      platform: state
      entity_id: switch.powermonitor
      from: 'False'
      to: 'True'
      for:
        seconds: 60
  # condition:
  #   condition: and
  #   conditions:
  #     - condition: state
  #       entity_id: switch.powermonitor
  #       state: 'on'
  #     - condition: state
  #       entity_id: device_tracker.eric_phone
  #       state: 'home'
  action:
    # - service: tts.google_say
    #   entity_id: media_player.
    #   data:
    #     message: 'The washer is finished.'
    - service: persistent_notification.create
      data:
        message: "Washing machine is finished"
        title: "Washing Machine"
    - service: notify.notify
      data:
        title: 'Washer Done'
        message: 'Washer has finished'
