# Washer Notification Sequence Done
- alias: 'Water Garden On'
  trigger:
    - platform: time
      at: "8:00:00"
    - platform: time
      at: "10:00:00"
    - platform: time
      at: "12:00:00"
    - platform: time
      at: "1:00:00"
    - platform: time
      at: "3:00:00"
    - platform: time
      at: "5:00:00"
  # condition:
  #   condition: and
  #   conditions:
  #     - condition: state
  #       entity_id: switch.powermonitor
  #       state: 'on'
  #     - condition: state
  #       entity_id: device_tracker.eric_phone
  #       state: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.drip_irrigation
    - service: notify.gmail
      data:
        title: 'Watering On'
        message: 'Watering has started'

######Turn off water after 5 iminutes
- alias: 'Water Garden Off'
  trigger:
    platform: state
    entity_id: switch.drip_irrigation
    to: 'on'
    for:
      minutes: 5
  action:
    - service: switch.turn_off
      entity_id: switch.drip_irrigation
    - service: notify.gmail
      data:
        title: 'Watering Off'
        message: 'Watering has ended'
