# Washer Notification Sequence Done
- alias: 'Water Garden On'
  trigger:
    - platform: time
      at: "6:00:00"
    - platform: time
      at: "8:00:00"
    - platform: time
      at: "10:00:00"
    - platform: time
      at: "12:00:00"
    - platform: time
      at: "14:00:00"
    - platform: time
      at: "16:00:00"
  # Do not start if raining
  condition:
    condition: numeric_state
    entity_id: sensor.dark_sky_precip_probability
    below: 50
  action:
    - service: switch.turn_on
      entity_id: switch.drip_irrigation

######Turn off water after 5 minutes
- alias: 'Water Garden Off'
  trigger:
    platform: state
    entity_id: switch.drip_irrigation
    to: 'on'
    for:
      minutes: 5
  action:
    - service: switch.turn_off
      entity_id: switch.drip_irrigation
    - service: notify.notify
      data:
        title: 'Watering Off'
        message: 'Watering has ended'

## Notify if watering skipped
- alias: 'Water Garden Skipped'
  trigger:
    - platform: time
      at: "6:01:00"
    - platform: time
      at: "8:01:00"
    - platform: time
      at: "10:01:00"
    - platform: time
      at: "12:01:00"
    - platform: time
      at: "14:01:00"
    - platform: time
      at: "16:01:00"
  # Do not start if raining
  #condition:
  #  condition: state
  #  entity_id: switch.drip_irrigation
  #  state: 'off'
  action:
    - service: notify.notify
      data:
        title: 'Watering Skipped'
        message: 'Rain probability is at '
