####Have your assistant welcome you home

- alias: 'Welcome Home'
  initial_state: 'on'
  trigger:
    platform: zone
    event: enter
    zone: zone.home
    entity_id: device_tracker.eric_phone

  action:
    - service: homeassistant.turn_on
      entity_id: script.greeting
